// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBabOjwJiRApAYTYzn6ZJwK8QwS8Csed-A',
    appId: '1:831903119606:web:60c0475c931b62e507d4d7',
    messagingSenderId: '831903119606',
    projectId: 'fluent-hands-b7be5',
    authDomain: 'fluent-hands-b7be5.firebaseapp.com',
    storageBucket: 'fluent-hands-b7be5.appspot.com',
    measurementId: 'G-YG6F77YZRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA72nIS0K3fqKfhTppzmw3vHrNgkmXmJvY',
    appId: '1:831903119606:android:1290d9105676c8d307d4d7',
    messagingSenderId: '831903119606',
    projectId: 'fluent-hands-b7be5',
    storageBucket: 'fluent-hands-b7be5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq5Xxyqy8eZZK8G4qbjsVhEIRfkx4mp_s',
    appId: '1:831903119606:ios:f2dc3e739c831c1307d4d7',
    messagingSenderId: '831903119606',
    projectId: 'fluent-hands-b7be5',
    storageBucket: 'fluent-hands-b7be5.appspot.com',
    iosBundleId: 'com.example.fluentHands',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq5Xxyqy8eZZK8G4qbjsVhEIRfkx4mp_s',
    appId: '1:831903119606:ios:f2dc3e739c831c1307d4d7',
    messagingSenderId: '831903119606',
    projectId: 'fluent-hands-b7be5',
    storageBucket: 'fluent-hands-b7be5.appspot.com',
    iosBundleId: 'com.example.fluentHands',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBabOjwJiRApAYTYzn6ZJwK8QwS8Csed-A',
    appId: '1:831903119606:web:f7312f2f1b2893af07d4d7',
    messagingSenderId: '831903119606',
    projectId: 'fluent-hands-b7be5',
    authDomain: 'fluent-hands-b7be5.firebaseapp.com',
    storageBucket: 'fluent-hands-b7be5.appspot.com',
    measurementId: 'G-JZ2F0T1140',
  );
}
