class AppAssets {
  static const String svgLogo = "assets/svg/logo.svg",
      onBoarding1 = "assets/svg/onBoarding1.svg",
      onBoarding2 = "assets/svg/onBoarding2.svg",
      onBoarding3 = "assets/svg/onBoarding3.svg",
      signUp = "assets/svg/signUp.svg",
      home = "assets/images/home.png",
      homeSelected = 'assets/images/home_selected.png',
      learn = "assets/images/learn.png",
      learnSelected = "assets/images/learn_selected.png",
      profile = "assets/images/profile.png",
      profileSelected = "assets/images/profile_selected.png",
      settings = "assets/images/settings.png",
      settingsSelected = "assets/images/settings_selected.png",
      googleIcon = "assets/images/google.png",
      learnTabSelected = "assets/images/learn_selected.png",
      learnTabUnSelected = "assets/images/learn_unselected.png",
      examSelected = "assets/images/exam_selected.png",
      examUnSelected = "assets/images/exam_unselected.png",
      next = "assets/images/next.png";
}
